import '@/styles/globals.css'
import '@/styles/App.css'
import Head from 'next/head'
import SignInPage from './signin'
import { useRouter } from 'next/router'
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  RedirectToSignIn,
} from "@clerk/nextjs";

const publicPages = ["/"]

export default function App({ Component, pageProps }) {
  const { pathname } = useRouter();
  const isPublicPage = publicPages.includes(pathname);
  
  return (     
      <ClerkProvider {...pageProps} >
        <Head>
            <title>Much Todo About Nothing</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
          </Head>
        {isPublicPage ? (
          <Component {...pageProps} />
        ) : ( <>    
            <SignedIn>
              <Component {...pageProps} />
            </SignedIn>
            <SignedOut>
              <RedirectToSignIn/>
            </SignedOut>
          </> )}
        </ClerkProvider>
  )
}
